# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weather
pod 'LTMorphingLabel'
pod 'GoogleMaps'
pod 'Firebase'
pod 'FirebaseRemoteConfig'
pod 'lottie-ios'
pod 'NVActivityIndicatorView'
pod 'Google-Mobile-Ads-SDK'
pod 'RealmSwift'
pod 'AlamofireNetworkActivityLogger', '~> 3.4'
pod 'Alamofire'

end
